// src/components/NavBar.svelte
<script lang="ts">
	import { Link } from "svelte-routing";
</script>

<nav>
	<ul>
		<li>
			<Link to="/">
				<img
					src="/favicon/ms-icon-310x310.png"
					alt="Logo"
					height="60"
				/>
				Dragons
			</Link>
		</li>
	</ul>
</nav>

<style lang="scss">
	@import "../styles/mixins";

	nav {
		max-width: 1200px;
	}
</style>

// components/nav-bar/index.tsx
import styles from "./index.module.scss";

import React from "react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";

const links = [];

export const Navbar: React.FC = () => {

  return (
    <nav className={styles.container}>
      <Link  href="/" passHref>
        <div>
            <Image
              src="/icons/logo.png"
              alt="Logo"
              height="40"
              width="19"
            />
            <h2>
              DragonBSC
            </h2>
        </div>
      </Link>
      <ul>
        <li></li>
      </ul>
    </nav>
  );
};
